### ISSUE TITLE
php server.php启动报错

### ISSUE THREAD

**Issue by dnslin** [kasuganosoras/SyncMusic#36]
```
root@ip-172-31-4-11:/www/wwwroot/SyncMusic# php server.php
PHP Fatal error:  Uncaught Error: Class 'Swoole\WebSocket\Server' not found in /www/wwwroot/SyncMusic/SyncMusic.php:65
Stack trace:
#0 /www/wwwroot/SyncMusic/server.php(82): SyncMusic->init()
#1 {main}
  thrown in /www/wwwroot/SyncMusic/SyncMusic.php on line 65

Fatal error: Uncaught Error: Class 'Swoole\WebSocket\Server' not found in /www/wwwroot/SyncMusic/SyncMusic.php:65
Stack trace:
#0 /www/wwwroot/SyncMusic/server.php(82): SyncMusic->init()
#1 {main}
  thrown in /www/wwwroot/SyncMusic/SyncMusic.php on line 65
****
```

**Comment by kasuganosoras** [comment]
没装 Swoole 扩展

**Comment by dnslin** [comment]
按照你贴的方法试过了 
curl https://tql.ink/swoole.sh | bash -  后
**php -m | grep swoole**
无任何输出回复

**Comment by kasuganosoras** [comment]
此方法仅适用于 OneinStack 安装的 PHP
如果是其他方式安装的需要自行编译 Swoole 然后安装
